apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ca1-services
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - ca1
  selector:
    matchLabels:
      metrics: enabled
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
