apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing
  namespace: ca1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pricing
  template:
    metadata:
      labels:
        app: pricing
    spec:
      containers:
        - name: pricing
          image: aq496/pricing:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pricing-svc
  namespace: ca1
spec:
  selector:
    app: pricing
  ports:
    - port: 80
      targetPort: 8080