apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: ca1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: aq496/gateway:1.0
          imagePullPolicy: Always
          env:
            - name: REQUIRE_AUTH
              value: "false"
            - name: BACKEND_TIMEOUT_MS
              value: "2000"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  namespace: ca1
spec:
  selector:
    app: gateway
  ports:
    - port: 80
      targetPort: 3000