apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ca1-gateway
  namespace: ca1
spec:
  ingressClassName: traefik
  rules:
    - host: ca1.local
      http:
        paths:
          - path: /api/checkout
            pathType: Prefix
            backend:
              service:
                name: http-interceptor-proxy
                port:
                  number: 8080
          - path: /api/ping
            pathType: Prefix
            backend:
              service:
                name: gateway-svc
                port:
                  number: 80
          - path: /api/arch
            pathType: Prefix
            backend:
              service:
                name: gateway-svc
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway-svc
                port:
                  number: 80