# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ca1-checkout
#   namespace: ca1
#   annotations:
#     traefik.ingress.kubernetes.io/router.priority: "100"
# spec:
#   ingressClassName: traefik
#   rules:
#     - host: ca1.local
#       http:
#         paths:
#           - path: /api/checkout
#             pathType: Prefix
#             backend:
#               service:
#                 name: http-interceptor-proxy
#                 port:
#                   number: 8080